### ISSUE TITLE
pep.xml files

### ISSUE THREAD

**Issue by glicky1** [chhh/batmass#12]
Hi, 

When I try to import and open pep.xml files I get this error massage.

umich.ms.batmass.data.core.api.DataLoadingException: Pep xml file had no retention time information.
	at umich.ms.batmass.filesupport.files.types.pepxml.providers.PepxmlFeaturesDataSource.load(PepxmlFeaturesDataSource.java:56)
	at umich.ms.batmass.filesupport.files.types.pepxml.providers.PepxmlFeaturesDataSource.load(PepxmlFeaturesDataSource.java:35)
	at umich.ms.batmass.data.core.api.DataContainer.load(DataContainer.java:101)
	at umich.ms.batmass.gui.viewers.featuretable.FeatureTableTopComponent$3.run(FeatureTableTopComponent.java:108)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:275)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

How can I open to these files?

Thank you

**Comment by chhh** [comment]
Looks like your pepxml file didn't have retention time (that's what it's called there iirc). RT is used to map IDs to the LCMS run as scan numbers are somewhat inconsistent. Where do those pepxml files come from?

**Comment by chhh** [comment]
No reply
