### ISSUE TITLE
could not load LC/MS data

### ISSUE THREAD

**Issue by suhande** [chhh/batmass#20]
Hi, I could not open a mzXML/mzML file, I can open it using openchrom or chemclipse, here is error message:
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at umich.ms.batmass.gui.viewers.spectrum.components.SpectraViewerComponent.<init>(SpectraViewerComponent.java:115)
	at umich.ms.batmass.gui.viewers.spectrum.SpectraViewerTopComponent.initSpectrumPanel(SpectraViewerTopComponent.java:157)
	at umich.ms.batmass.gui.viewers.spectrum.SpectraViewerTopComponent.access$200(SpectraViewerTopComponent.java:64)
	at umich.ms.batmass.gui.viewers.spectrum.SpectraViewerTopComponent$2.run(SpectraViewerTopComponent.java:115)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by suhande** [comment]
[https://github.com/HUPO-PSI/mzML/tree/master/examples]
here are the files i used

**Comment by chhh** [comment]
I encourage you to try some real world mzML files converted with `msconvert` program from ProteoWizard.
Which file specifically could you not view?
