### ISSUE TITLE
does not recognize mzrt.csv

### ISSUE THREAD

**Issue by lorenzgerber** [chhh/batmass#6]
I try to import features as mzrt.csv files but they are not recognised.
I'm on BatMass 201411181905, with Java 1.8.0_111 using a OSX 10.12.5

**Comment by rsalek** [comment]
Have same issue, with XCMS.CSV I created for ML. Followed your example.

**Comment by lorenzgerber** [comment]
@rsalek Reza, I just got it to work. I reinstalled from a recent download, fixed the permission issue and then after startup, the application updates the plugins. Then mzrt.csv import is available
Cheers
Lorenz

**Comment by rsalek** [comment]
Is that correcting file:/G:/projects/netbeans/BatMass/build/updates/updates.xml ?

**Comment by lorenzgerber** [comment]
For me it did. I got the exact same error. I think my issue was that because batmass didn't run with the install script (OSX, due to the permission issues), I started to run it out of the dowloaded directory, which somehow worked, but as such, the plugin update was broken.
I removed the whole installation (hidden directory in home .batmass), downloaded a fresh tgz and finally it worked. I also tried on Linux (ubuntu 16.04), which also worked just fine.

**Comment by rsalek** [comment]
can you share your "mzrt.csv" pls

**Comment by lorenzgerber** [comment]
hmm, the mzrt.csv's are really as simple as it sounds. Here is an example that works for me:
[someTargets.mzrt.csv](https://gist.github.com/lorenzgerber/4cce9ee20c93b501d6868eb7438d4cf1)

**Comment by lorenzgerber** [comment]
@rsalek Here are my configurations settings, they are different to yours:
[configuration settings](https://www.dropbox.com/s/nvsxhtdc9hxp4o6/Screen%20Shot%202017-05-20%20at%2023.12.42.png?dl=0)

**Comment by rsalek** [comment]
Thx, worked 👍, just now need to figure out how to overlay them :)

**Comment by chhh** [comment]
Hi guys, sorry, I missed the conversation. 
I guess you've seen this one tutorial: http://www.batmass.org/tutorial/custom-drawing/
To overlay:
- Select both the mzrt.csv file and the mzml/mzxml file (left click while holding Ctrl)
- With both files selected, right click any of the two
- In the dropdown menu select **Feature Overlay**

**Comment by rsalek** [comment]
Hi, got it working but can't see the boxes, question rt  in second is ok or have to be in min? I also get Java error sorryy for the dump!

---------
java.lang.ArrayIndexOutOfBoundsException: -4952
	at umich.ms.batmass.gui.viewers.map2d.components.BaseMap2D.addPeakRaw(BaseMap2D.java:651)
	at umich.ms.batmass.gui.viewers.map2d.components.BaseMap2D.fillMapFromScans(BaseMap2D.java:289)
	at umich.ms.batmass.gui.viewers.map2d.components.Map2DZoomLevel.initMapAxesColors(Map2DZoomLevel.java:82)
	at umich.ms.batmass.gui.viewers.map2d.components.Map2DZoomLevel.<init>(Map2DZoomLevel.java:71)
	at umich.ms.batmass.gui.viewers.map2d.components.Map2DPanel.zoom(Map2DPanel.java:802)
	at umich.ms.batmass.gui.viewers.map2d.components.Map2DPanel$BusHandler.eventbusHandlerFeatureClickEvent(Map2DPanel.java:1463)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[catch] at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:41)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:66)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:46)
	at net.engio.mbassy.bus.MBassador.publish(MBassador.java:46)
	at umich.ms.batmass.gui.viewers.featuretable.components.FeatureTable$BusHandler.featureClicked(FeatureTable.java:116)
	at umich.ms.batmass.gui.viewers.featuretable.components.FeatureTable$1.mousePressed(FeatureTable.java:77)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by chhh** [comment]
Has to be in minutes - there's no way to differentiate between time units. Everything in batmass and msftbx is in minutes.

**Comment by rsalek** [comment]
I that explains it ... thx mine is:
xmzLo	mzHi	rtLo	rtHi	color	opacity
57.97554649	57.97562426	67.846	69.6165	R=255,G=127,B=80	0.1
61.98828098	61.98834594	53.5205	59.0379	R=255,G=127,B=81	0.1
63.61907023	63.62289588	346.002	352.352	R=255,G=127,B=82	0.1
70.94597034	70.94624015	52.0364	54.976	R=255,G=127,B=83	0.1
72.94260526	72.94320084	52.9876	54.976	R=255,G=127,B=84	0.1

**Comment by chhh** [comment]
@rsalek there's also an extra **x** in **mzLo** column name.  If you're using **color** it has to be in hex starting with **#**. e.g. `#FF7F50`, I believe, for your color.

**Comment by rsalek** [comment]
just copied it from your tools it is:
mzLo	mzHi	rtLo	rtHi	color	opacity
57.97554649	57.97562426	67.846	69.6165	#ff7f50	0.1
61.98828098	61.98834594	53.5205	59.0379	#ff7f50	0.1
63.61907023	63.62289588	346.002	352.352	#ff7f50	0.1
70.94597034	70.94624015	52.0364	54.976	#ff7f50	0.1

**Comment by chhh** [comment]
@rsalek is that working now? Because the error in the dump that you've sent was related to something different, I believe.

**Comment by rsalek** [comment]
Seems working now @chhh with rt in min, thx
